---
title: "Passwords"
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
library(tidytuesdayR)
library(tidyverse)
library(ggplot2)
library(plotrix)
library(ggthemes)
library(dplyr)
library(magrittr)

## Global options
options(max.print="75")
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	comment = NA,
	prompt = FALSE,
	tidy = TRUE
)
opts_knit$set(width=75)

```

# Get the Data
```{r setup 2}
passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')

# Or read in with tidytuesdayR package (https://github.com/thebioengineer/tidytuesdayR)
# PLEASE NOTE TO USE 2020 DATA YOU NEED TO UPDATE tidytuesdayR from GitHub

# Either ISO-8601 date or year/week works!

# Install via devtools::install_github("thebioengineer/tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load('2020-01-14') 
tuesdata <- tidytuesdayR::tt_load(2020, week = 3)


passwords <- tuesdata$passwords
```

# Einleitung
Passwörter sollten sicher sein.

Quelle: [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-05-26/readme.md)

# Daten
```{r visualisierung}
category %>% count()

```
  Für später:
  sum_df <- passwords %>%
filter(!is.na(category)) %>%
group_by(offline_crack_sec, strength)

sum_df %>% ggplot() +
  aes(x = offline_crack_sec) +
  aes(y = category) +
  aes(fill = strength)